global with sharing class DoctorActionQueueable implements Queueable{


    public void execute(QueueableContext context) {
////SearchDoctorsController sdc = new SearchDoctorsController();
////       sdc.createDoctor();
//
//        if (doctorWrapper.lastName != '' && doctorWrapper.email != '') {
//            service.insertDoctor(wrapperToDoctor(doctorWrapper));
//            closeModal();
//            searchDoctor.clear();
//        } else {
//            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Last Name and Email can\'t be empty'));
//        }
    }

}